Remove some extraneous lines for the first time :)

diff --git a/gxadmin b/gxadmin
--- a/gxadmin
+++ b/gxadmin
@@ -463,7 +463,7 @@ gdpr_safe() {
 	fi
 }
 
-query_latest_users() { ## query latest-users: 40 recently registered users
+query_latest-users() { ## query latest-users: 40 recently registered users
 	handle_help "$@" <<-EOF
 		Returns 40 most recently registered users
 
@@ -495,7 +495,7 @@ query_latest_users() { ## query latest-users: 40 recently registered users
 	EOF
 }
 
-query_tool_usage() { ## query tool-usage: Counts of tool runs
+query_tool-usage() { ## query tool-usage: Counts of tool runs
 	handle_help "$@" <<-EOF
 		    $ gxadmin tool-usage
 		                                    tool_id                                 | count
@@ -523,7 +523,7 @@ query_tool_usage() { ## query tool-usage: Counts of tool runs
 	EOF
 }
 
-query_tool_popularity() { ## query tool-popularity [months|24]: Most run tools by month
+query_tool-popularity() { ## query tool-popularity [months|24]: Most run tools by month
 	handle_help "$@" <<-EOF
 		See most popular tools by month
 
@@ -558,7 +558,7 @@ query_tool_popularity() { ## query tool-popularity [months|24]: Most run tools b
 	EOF
 }
 
-query_job_info() { ## query job-info <id>: Information about a specific job
+query_job-info() { ## query job-info <id>: Information about a specific job
 	handle_help "$@" <<-EOF
 		    $ gxadmin query job-info 1
 		     tool_id | state | username |        create_time         | job_runner_name | job_runner_external_id
@@ -716,7 +716,7 @@ EOF
 	printf "$template3" "$input_ds_tbl" "$output_ds_tbl"
 }
 
-query_workflow_connections() { ## query workflow-connections [--all]: The connections of tools, from output to input, in the latest (or all) versions of user workflows
+query_workflow-connections() { ## query workflow-connections [--all]: The connections of tools, from output to input, in the latest (or all) versions of user workflows
 	handle_help "$@" <<-EOF
 		This is used by the usegalaxy.eu tool prediction workflow, allowing for building models out of tool connections in workflows.
 
@@ -769,7 +769,7 @@ query_workflow_connections() { ## query workflow-connections [--all]: The connec
 	EOF
 }
 
-query_datasets_created_daily() { ## query datasets-created-daily: The min/max/average/p95/p99 of total size of datasets created in a single day.
+query_datasets-created-daily() { ## query datasets-created-daily: The min/max/average/p95/p99 of total size of datasets created in a single day.
 	handle_help "$@" <<-EOF
 		    $ gxadmin query datasets-created-daily
 		       min   |  avg   | perc_95 | perc_99 |  max
@@ -795,7 +795,7 @@ query_datasets_created_daily() { ## query datasets-created-daily: The min/max/av
 	EOF
 }
 
-query_largest_collection() { ## query largest-collection: Returns the size of the single largest collection
+query_largest-collection() { ## query largest-collection: Returns the size of the single largest collection
 	handle_help "$@" <<-EOF
 	EOF
 
@@ -813,7 +813,7 @@ query_largest_collection() { ## query largest-collection: Returns the size of th
 	EOF
 }
 
-query_queue_time() { ## query queue-time <tool_id>: The average/95%/99% a specific tool spends in queue state.
+query_queue-time() { ## query queue-time <tool_id>: The average/95%/99% a specific tool spends in queue state.
 	handle_help "$@" <<-EOF
 		    $ gxadmin query queue-time toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_geneBody_coverage/2.6.4.3
 		           min       |     perc_95     |     perc_99     |       max
@@ -880,7 +880,7 @@ query_queue() { ## query queue: Brief overview of currently running jobs
 	EOF
 }
 
-query_queue_overview() { ## query queue-overview [--short-tool-id]: View used mostly for monitoring
+query_queue-overview() { ## query queue-overview [--short-tool-id]: View used mostly for monitoring
 	handle_help "$@" <<-EOF
 		Primarily for monitoring of queue. Optimally used with 'iquery' and passed to Telegraf.
 
@@ -923,7 +923,7 @@ query_queue_overview() { ## query queue-overview [--short-tool-id]: View used mo
 	EOF
 }
 
-query_queue_detail() { ## query queue-detail [--all]: Detailed overview of running and queued jobs
+query_queue-detail() { ## query queue-detail [--all]: Detailed overview of running and queued jobs
 	handle_help "$@" <<-EOF
 		    $ gxadmin query queue-detail
 		      state  |   id    |  extid  |                                 tool_id                                   | username | time_since_creation
@@ -969,7 +969,7 @@ query_queue_detail() { ## query queue-detail [--all]: Detailed overview of runni
 	EOF
 }
 
-query_runtime_per_user() { ## query runtime-per-user <email>: computation time of user (by email)
+query_runtime-per-user() { ## query runtime-per-user <email>: computation time of user (by email)
 	handle_help "$@" <<-EOF
 		    $ gxadmin query runtime-per-user hxr@informatik.uni-freiburg.de
 		       sum
@@ -994,7 +994,7 @@ query_runtime_per_user() { ## query runtime-per-user <email>: computation time o
 	EOF
 }
 
-query_jobs_nonterminal() { ## query jobs-nonterminal [username|id|email]: Job info of nonterminal jobs separated by user
+query_jobs-nonterminal() { ## query jobs-nonterminal [username|id|email]: Job info of nonterminal jobs separated by user
 	handle_help "$@" <<-EOF
 		You can request the user information by username, id, and user email
 
@@ -1045,7 +1045,7 @@ query_jobs_nonterminal() { ## query jobs-nonterminal [username|id|email]: Job in
 	EOF
 }
 
-query_jobs_per_user() { ## query jobs-per-user <email>: Number of jobs run by a specific user
+query_jobs-per-user() { ## query jobs-per-user <email>: Number of jobs run by a specific user
 	handle_help "$@" <<-EOF
 		    $ gxadmin query jobs-per-user hxr@informatik.uni-freiburg.de
 		     count
@@ -1064,7 +1064,7 @@ query_jobs_per_user() { ## query jobs-per-user <email>: Number of jobs run by a 
 	EOF
 }
 
-query_recent_jobs() { ## query recent-jobs <hours>: Jobs run in the past <hours> (in any state)
+query_recent-jobs() { ## query recent-jobs <hours>: Jobs run in the past <hours> (in any state)
 	handle_help "$@" <<-EOF
 		    $ gxadmin query recent-jobs 2.1
 		       id    |     date_trunc      |      tool_id          | state |    username
@@ -1146,7 +1146,7 @@ query_training_members() { ## query training-members <tr_id>: List users in a sp
 	EOF
 }
 
-query_training_memberof() { ## query training-memberof <username>: List trainings that a user is part of
+query_training-memberof() { ## query training-memberof <username>: List trainings that a user is part of
 	handle_help "$@" <<-EOF
 	EOF
 
@@ -1165,7 +1165,7 @@ query_training_memberof() { ## query training-memberof <username>: List training
 	EOF
 }
 
-query_training_remove_member() { ## query training-remove-member <training> <username> [YESDOIT]: Remove a user from a training
+query_training-remove-member() { ## query training-remove-member <training> <username> [YESDOIT]: Remove a user from a training
 	handle_help "$@" <<-EOF
 	EOF
 
@@ -1197,7 +1197,7 @@ query_training_remove_member() { ## query training-remove-member <training> <use
 	fi
 }
 
-query_training_queue() { ## query training-queue <training_id>: Jobs currently being run by people in a given training
+query_training-queue() { ## query training-queue <training_id>: Jobs currently being run by people in a given training
 	handle_help "$@" <<-EOF
 		Finds all jobs by people in that queue (including things they are executing that are not part of a training)
 
@@ -1285,7 +1285,7 @@ EOF
 	echo "$dump_config_python" | python
 }
 
-query_disk_usage() { ## query disk-usage [--nice]: Disk usage per object store.
+query_disk-usage() { ## query disk-usage [--nice]: Disk usage per object store.
 	handle_help "$@" <<-EOF
 		Query the different object stores referenced in your Galaxy database
 
@@ -1326,7 +1326,7 @@ query_disk_usage() { ## query disk-usage [--nice]: Disk usage per object store.
 	EOF
 }
 
-query_user_info() { ## query user-info <user_id|username|email>: Quick overview of a Galaxy user in your system
+query_user-info() { ## query user-info <user_id|username|email>: Quick overview of a Galaxy user in your system
 	handle_help "$@" <<-EOF
 		This command lets you quickly find out information about a user. The output is formatted as markdown by default.
 
@@ -1461,7 +1461,7 @@ EOF
 	printf "$template" $results "$group_membership" "$role_membership" "$recent_jobs2" "$largest_histories"
 }
 
-query_users_count() { ## query users-count: Shows sums of active/external/deleted/purged accounts
+query_users-count() { ## query users-count: Shows sums of active/external/deleted/purged accounts
 	handle_help "$@" <<-EOF
 		     active | external | deleted | purged | count
 		    --------+----------+---------+--------+-------
@@ -1485,7 +1485,7 @@ query_users_count() { ## query users-count: Shows sums of active/external/delete
 	EOF
 }
 
-query_tool_last_used_date() { ## query tool-last-used-date: When was the most recent invocation of every tool
+query_tool-last-used-date() { ## query tool-last-used-date: When was the most recent invocation of every tool
 	handle_help "$@" <<-EOF
 		Example invocation:
 
@@ -1507,7 +1507,7 @@ query_tool_last_used_date() { ## query tool-last-used-date: When was the most re
 	EOF
 }
 
-query_users_total() { ## query users-total: Total number of Galaxy users (incl deleted, purged, inactive)
+query_users-total() { ## query users-total: Total number of Galaxy users (incl deleted, purged, inactive)
 	handle_help "$@" <<-EOF
 	EOF
 
@@ -1519,7 +1519,7 @@ query_users_total() { ## query users-total: Total number of Galaxy users (incl d
 	EOF
 }
 
-query_groups_list() { ## query groups-list: List all groups known to Galaxy
+query_groups-list() { ## query groups-list: List all groups known to Galaxy
 	handle_help "$@" <<-EOF
 	EOF
 
@@ -1537,7 +1537,7 @@ query_groups_list() { ## query groups-list: List all groups known to Galaxy
 	EOF
 }
 
-query_collection_usage() { ## query collection-usage: Information about how many collections of various types are used
+query_collection-usage() { ## query collection-usage: Information about how many collections of various types are used
 	handle_help "$@" <<-EOF
 	EOF
 
@@ -1557,7 +1557,7 @@ query_collection_usage() { ## query collection-usage: Information about how many
 	EOF
 }
 
-query_ts_repos() { ## query ts-repos: Counts of toolshed repositories by toolshed and owner.
+query_ts-repos() { ## query ts-repos: Counts of toolshed repositories by toolshed and owner.
 	handle_help "$@" <<-EOF
 	EOF
 
@@ -1574,7 +1574,7 @@ query_ts_repos() { ## query ts-repos: Counts of toolshed repositories by toolshe
 	EOF
 }
 
-query_active_users() { ## query active-users [weeks]: Count of users who ran jobs in past 1 week (default = 1)
+query_active-users() { ## query active-users [weeks]: Count of users who ran jobs in past 1 week (default = 1)
 	handle_help "$@" <<-EOF
 		Unique users who ran jobs in past week:
 
@@ -1612,7 +1612,7 @@ query_active_users() { ## query active-users [weeks]: Count of users who ran job
 	EOF
 }
 
-query_tool_metrics() { ## query tool-metrics <tool_id> <metric_id> [--like]: See values of a specific metric
+query_tool-metrics() { ## query tool-metrics <tool_id> <metric_id> [--like]: See values of a specific metric
 	handle_help "$@" <<-EOF
 		A good way to use this is to fetch the memory usage of a tool and then
 		do some aggregations. The following requires [data_hacks](https://github.com/bitly/data_hacks)
@@ -1656,7 +1656,7 @@ query_tool_metrics() { ## query tool-metrics <tool_id> <metric_id> [--like]: See
 	EOF
 }
 
-query_tool_available_metrics() { ## query tool-available-metrics <tool_id>: list all available metrics for a given tool
+query_tool-available-metrics() { ## query tool-available-metrics <tool_id>: list all available metrics for a given tool
 	handle_help "$@" <<-EOF
 		Gives a list of available metrics, which can then be used to query.
 
@@ -1683,7 +1683,7 @@ query_tool_available_metrics() { ## query tool-available-metrics <tool_id>: list
 	EOF
 }
 
-query_month_data(){ ## query monthly-data [year]: Number of active users per month, running jobs
+query_monthly-data(){ ## query monthly-data [year]: Number of active users per month, running jobs
 	handle_help "$@" <<-EOF
 		Find out how much data was ingested or created by Galaxy during the past months.
 
@@ -1721,7 +1721,7 @@ query_month_data(){ ## query monthly-data [year]: Number of active users per mon
 	EOF
 }
 
-query_month_users(){ ## query monthly-users [year]: Number of active users per month, running jobs
+query_monthly-users(){ ## query monthly-users [year]: Number of active users per month, running jobs
 	handle_help "$@" <<-EOF
 		Number of unique users each month who ran jobs. NOTE: does not include anonymous users.
 
@@ -1757,7 +1757,7 @@ query_month_users(){ ## query monthly-users [year]: Number of active users per m
 	EOF
 }
 
-query_month_jobs(){ ## query monthly-jobs [year]: Number of jobs run each month
+query_monthly-jobs(){ ## query monthly-jobs [year]: Number of jobs run each month
 	handle_help "$@" <<-EOF
 		Count jobs run each month
 
@@ -1797,7 +1797,7 @@ query_month_jobs(){ ## query monthly-jobs [year]: Number of jobs run each month
 
 }
 
-query_job_history() { ## query job-history <id>: Job state history for a specific job
+query_job-history() { ## query job-history <id>: Job state history for a specific job
 	handle_help "$@" <<-EOF
 		    $ gxadmin query job-history 4384025
 		            time         |  state
@@ -1820,7 +1820,7 @@ query_job_history() { ## query job-history <id>: Job state history for a specifi
 	EOF
 }
 
-query_job_inputs() { ## query job-inputs <id>: Input datasets to a specific job
+query_job-inputs() { ## query job-inputs <id>: Input datasets to a specific job
 	handle_help "$@" <<-EOF
 	EOF
 	assert_count $# 1 "Missing Job ID"
@@ -1847,7 +1847,7 @@ query_job_inputs() { ## query job-inputs <id>: Input datasets to a specific job
 	EOF
 }
 
-query_job_outputs() { ## query job-outputs <id>: Output datasets from a specific job
+query_job-outputs() { ## query job-outputs <id>: Output datasets from a specific job
 	handle_help "$@" <<-EOF
 	EOF
 
@@ -1876,7 +1876,7 @@ query_job_outputs() { ## query job-outputs <id>: Output datasets from a specific
 	EOF
 }
 
-query_old_histories(){ ## query old-histories <weeks>: Lists histories that haven't been updated (used) for <weeks>
+query_old-histories(){ ## query old-histories <weeks>: Lists histories that haven't been updated (used) for <weeks>
 	handle_help "$@" <<-EOF
 		Histories and their users who haven't been updated for a specified number of weeks. Default number of weeks is 15.
 
@@ -1923,7 +1923,7 @@ query_old_histories(){ ## query old-histories <weeks>: Lists histories that have
 	EOF
 }
 
-query_errored_jobs(){ ## query errored-jobs <hours>: Lists jobs that errored in the last N hours.
+query_errored-jobs(){ ## query errored-jobs <hours>: Lists jobs that errored in the last N hours.
 	handle_help "$@" <<-EOF
 		Lists details of jobs that have status = 'error' for the specified number of hours. Default = 24 hours
 
@@ -1983,7 +1983,7 @@ query_errored_jobs(){ ## query errored-jobs <hours>: Lists jobs that errored in 
 	#EOF
 #}
 
-query_failed_terminal_datasets() { ## query failed-terminal-datasets: Identify the list of datasets which had issues
+query_failed-terminal-datasets() { ## query failed-terminal-datasets: Identify the list of datasets which had issues
 	handle_help "$@" <<-EOF
 		Whenever an admin marks a job as failed manually (e.g. by updating the
 		state in the database), the output datasets are not accordingly updated
@@ -2205,52 +2205,16 @@ cmdlist() {
 obtain_query() {
 	query_name="$1"; shift
 
-	case "$query_name" in
-		active-users            ) query_active_users             "$@" ;;
-		collection-usage        ) query_collection_usage         "$@" ;;
-		datasets-created-daily  ) query_datasets_created_daily   "$@" ;;
-		disk-usage              ) query_disk_usage               "$@" ;;
-		errored-jobs            ) query_errored_jobs             "$@" ;;
-		failed-terminal-datasets) query_failed_terminal_datasets "$@" ;;
-		groups-list             ) query_groups_list              "$@" ;;
-		job-history             ) query_job_history              "$@" ;;
-		job-info                ) query_job_info                 "$@" ;;
-		job-inputs              ) query_job_inputs               "$@" ;;
-		job-outputs             ) query_job_outputs              "$@" ;;
-		jobs-nonterminal        ) query_jobs_nonterminal         "$@" ;;
-		jobs-per-user           ) query_jobs_per_user            "$@" ;;
-		largest-collection      ) query_largest_collection       "$@" ;;
-		latest-users            ) query_latest_users             "$@" ;;
-		monthly-data            ) query_month_data               "$@" ;;
-		monthly-jobs            ) query_month_jobs               "$@" ;;
-		monthly-users           ) query_month_users              "$@" ;;
-		old-histories           ) query_old_histories            "$@" ;;
-		queue                   ) query_queue                    "$@" ;;
-		queue-detail            ) query_queue_detail             "$@" ;;
-		queue-overview          ) query_queue_overview           "$@" ;;
-		queue-time              ) query_queue_time               "$@" ;;
-		recent-jobs             ) query_recent_jobs              "$@" ;;
-		runtime-per-user        ) query_runtime_per_user         "$@" ;;
-		tool-available-metrics  ) query_tool_available_metrics   "$@" ;;
-		tool-last-used-date     ) query_tool_last_used_date      "$@" ;;
-		tool-metrics            ) query_tool_metrics             "$@" ;;
-		tool-usage              ) query_tool_usage               "$@" ;;
-		tool-popularity         ) query_tool_popularity          "$@" ;;
-		training                ) query_training                 "$@" ;;
-		training-memberof       ) query_training_memberof        "$@" ;;
-		training-members        ) query_training_members         "$@" ;;
-		training-queue          ) query_training_queue           "$@" ;;
-		training-remove-member  ) query_training_remove_member   "$@" ;;
-		ts-repos                ) query_ts_repos                 "$@" ;;
-		user-details            ) query_user_info                "$@" ;;
-		user-info               ) query_user_info                "$@" ;;
-		users-count             ) query_users_count              "$@" ;;
-		users-total             ) query_users_total              "$@" ;;
-		workflow-connections    ) query_workflow_connections     "$@" ;;
+	# Check that FN exists
+	fn="query_${query_name}"
+	echo "going to run $fn"
+	LC_ALL=C type $fn | grep -q 'function'
 
-		# default
-		* ) export QUERY="ERROR" ;;
-	esac
+	if (( $? == 0 )); then
+		query_${query_name} "$@";
+	else
+		export QUERY="ERROR"
+	fi
 }
 
 query() {
